name: UU-INFOFP-Game
version: 0.1.0.0
github: "Fusion86/UU-INFOFP-Game"
license: OtherLicense
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Fusion86/UU-INFOFP-Game#readme>

dependencies:
  - base >= 4.7 && < 5
  - directory
  - containers
  - filepath
  - text
  - bytestring
  - pretty-simple
  - sdl2
  - sdl2-ttf
  - gloss
  - gloss-juicy
  - gloss-sdl2-surface
  - JuicyPixels
  - JuicyPixels-extra
  - xml

library:
  source-dirs: src

executables:
  UU-INFOFP-Game-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - UU-INFOFP-Game

tests:
  UU-INFOFP-Game-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - UU-INFOFP-Game
